version: '3.3'
services:
    ddnsto:
        container_name: ddnsto
        restart: always
        network_mode: host
        environment:
            - TOKEN=15a9cc19-8f54-4bfc-a73a-d4a706be37e8
            - DEVICE_IDX=0
            - PUID=0
            - PGID=0
        volumes:
            - '/etc/localtime:/etc/localtime:ro'
        image: 'linkease/ddnsto:3.0.0
