version: '3.3'
services:
    drpy:
            image: hjdhnx/drpy
            container_name: drpy
            restart: always
            environment:
                - TZ=Asia/Shanghai
            ports:
                - 5705:5705
                - 9001:9001
            volumes:
                - ./:/root/sd/pywork/dr_py
